#!/bin/bash
tr "A" "Z" | tr "c" "e"[D[D[[D[D[D[C[C[C[[D[D[D[D[D[D[C[C[[[C[C[C[C[C[C[C[D[D[D[D[D[D[D[D[D[D[D[D[D[D[[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D
