#!/bin/bash
sudo chown --from=gullaume betty hello[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[Di[C[D[Dl[D[Di[D[[C=guilla[C[C[C[C[C[C[C[Csudo chown --from=guillaume betty hello
